examples: uartpb: up version of typer to 0.4.1
Due to this error [1]:
  Traceback (most recent call last):
    File "/mcu-firmware/examples/sys_sysmon/sysmon-client.py", line 9, in <module>
      import typer
    File "/mcu-firmware/venv/lib/python3.10/site-packages/typer/__init__.py", line 12, in <module>
      from click.termui import get_terminal_size as get_terminal_size
  ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/mcu-firmware/venv/lib/python3.10/site-packages/click/termui.py)

[1] https://github.com/tiangolo/typer/issues/377

Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>